# Input/Output
input.dir=./input/
output.msc=./out/msc.csv
output.smsc=./out/smsc.csv
output.pgw=./out/pgw.csv

# SFTP MSC
sftp.msc.host=localhost
sftp.msc.port=2221

# SFTP SMSC
sftp.smsc.host=localhost
sftp.smsc.port=2222

# SFTP PGW
sftp.pgw.host=localhost
sftp.pgw.port=2223

# Postpaid
sftp.postpaid.host=localhost
sftp.postpaid.port=2224

# Prepaid
sftp.prepaid.host=localhost
sftp.prepaid.port=2225

# Credentials
sftp.username=admin
sftp.password=123456

# Remote upload folder inside containers
sftp.remote.dir=/upload/
