# Input/Output
input.dir=./in/
output.msc=./out/msc.csv
output.smsc=./out/smsc.csv
output.pgw=./out/pgw.csv

# SFTP MSC
sftp.msc.host=localhost
sftp.msc.port=2221

# SFTP SMSC
sftp.smsc.host=localhost
sftp.smsc.port=2222

# SFTP PGW
sftp.pgw.host=localhost
sftp.pgw.port=2223

sftp.postpaid.host=localhost
sftp.postpaid=2224


sftp.prepaid=localhost
sftp.prepaid.port=2225

# SFTP Credentials
sftp.username=admin
sftp.password=123456
sftp.remote.dir=/upload/