# Number of SFTP servers
sftp.servers.count=3

# Server 1
sftp.server.1.host=localhost
sftp.server.1.port=22
sftp.server.1.user=admin
sftp.server.1.password=123456
sftp.server.1.remote.dir=/upload/

# Server 2
sftp.server.2.host=localhost
sftp.server.2.port=222
sftp.server.2.user=admin
sftp.server.2.password=123456
sftp.server.2.remote.dir=/upload/

# Server 3
sftp.server.3.host=localhost
sftp.server.3.port=2222
sftp.server.3.user=admin
sftp.server.3.password=123456
sftp.server.3.remote.dir=/upload/